export const USER_TYPE_SUBSCRIBER = 'SUBSCRIBER';
export const USER_TYPE_GOFUNDIS = 'GOFUNDIS';
export const USER_TYPE_ALL = 'ALL';

export const TASK_STATYS_COMPLETED = 'COMPLETED';
export const TASK_STATYS_ASSIGNED = 'ASSIGNED';
export const TASK_STATYS_UNASSIGNED = 'UNASSIGNED';
export const TASK_STATYS_DECLINED = 'DECLINED';
export const TASK_STATYS_CANCELLED = 'CANCELLED';
