export const USER_TYPE_SUBSCRIBER = 'SUBSCRIBER';
export const USER_TYPE_GOFUNDIS = 'GOFUNDIS';
export const USER_TYPE_ALL = 'ALL';
export const USER_TYPES = [USER_TYPE_SUBSCRIBER, USER_TYPE_GOFUNDIS, USER_TYPE_ALL];

export const TASK_STATYS_COMPLETED = 'COMPLETED';
export const TASK_STATYS_ASSIGNED = 'ASSIGNED';
export const TASK_STATYS_UNASSIGNED = 'UNASSIGNED';
export const TASK_STATYS_DECLINED = 'DECLINED';
export const TASK_STATYS_CANCELLED = 'CANCELLED';

export const CATEGORY_ALL = 'ALL CATEGORIES';
export const CATEGORY_NEW_INSTALL_DECODER = 'INSTALLATION - DECODER';
export const CATEGORY_NEW_INSTALL_SIGNAL = 'INSTALLATION - ANTENNA';
export const CATEGORY_NEW_INSTALL_ERROR = 'INSTALLATION - OTHER';
export const CATEGORY_REPAIR_INSTALL_DECODER = 'REPAIR - DECODER';
export const CATEGORY_REPAIR_INSTALL_SIGNAL = 'REPAIR - ANTENNA';
export const CATEGORY_REPAIR_INSTALL_ERROR = 'REPAIR - OTHER';

export const GOFUNDIS_STATYS_OFFLINE = 'OFFLINE';
export const GOFUNDIS_STATYS_ONLINE = 'ONLINE';
export const GOFUNDIS_ALL = 'ALL';

export const SUBSCRIBERS_ALL = 'subscriber';

export const K_MARGIN_TOP = 30;
export const K_MARGIN_RIGHT = 30;
export const K_MARGIN_BOTTOM = 30;
export const K_MARGIN_LEFT = 30;
export const MAP_ZOOM = 5;
